server:
  port: 8081
spring:
  config:
    active:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:6969/sports_league
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
